from __future__ import annotations

MAX_HAND_SIZE = 10
MAX_NUM_MONSTERS_IN_GROUP = 5
MAX_CHARACTER_HEALTH = 1000
MAX_CHARACTER_BLOCK = 1000
MAX_POWER_STACKS = 1000
PLAYER_MAX_ENERGY = 1000
RELIC_MIN_INDICATOR = -1000
RELIC_MAX_INDICATOR = 1000
CARD_MAX_DAMAGE = 1000
CARD_MAX_BLOCK = 1000
CARD_MAX_MAGIC_NUMBER = 1000
CARD_MAX_COST = 100
MAX_POTION_SLOTS = 5
MAX_CARD_GROUP_SIZE = 100
MONSTER_MAX_NUM_MOVES = 10
MAP_HEIGHT = 15
MAP_WIDTH = 7
MAP_PATH_DENSITY = 6
ACTION_0_LEN = 1 + MAX_HAND_SIZE + 2 * MAX_POTION_SLOTS
ACTION_1_LEN = 1 + MAX_NUM_MONSTERS_IN_GROUP
ACTION_1_ALL_FALSE_SLICE = [False] * ACTION_1_LEN
ACTION_1_SINGLE_TRUE = [False] * (ACTION_1_LEN - 1) + [True]
